# CMake generated Testfile for 
# Source directory: /home/nxclab/shan/src/moe-test/src/ggml/tests
# Build directory: /home/nxclab/shan/src/moe-test/lib/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-opt "/home/nxclab/shan/src/moe-test/lib/bin/test-opt")
set_tests_properties(test-opt PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-opt.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;191;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-quantize-fns "/home/nxclab/shan/src/moe-test/lib/bin/test-quantize-fns")
set_tests_properties(test-quantize-fns PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-quantize-fns.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;200;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-quantize-perf "/home/nxclab/shan/src/moe-test/lib/bin/test-quantize-perf")
set_tests_properties(test-quantize-perf PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-quantize-perf.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;209;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-mul-mat0 "/home/nxclab/shan/src/moe-test/lib/bin/test-mul-mat0")
set_tests_properties(test-mul-mat0 PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-mul-mat0.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;222;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-mul-mat2 "/home/nxclab/shan/src/moe-test/lib/bin/test-mul-mat2")
set_tests_properties(test-mul-mat2 PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-mul-mat2.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;253;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test0 "/home/nxclab/shan/src/moe-test/lib/bin/test0")
set_tests_properties(test0 PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test0.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;266;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-pool "/home/nxclab/shan/src/moe-test/lib/bin/test-pool")
set_tests_properties(test-pool PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-pool.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;278;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-arange "/home/nxclab/shan/src/moe-test/lib/bin/test-arange")
set_tests_properties(test-arange PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-arange.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;290;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-timestep_embedding "/home/nxclab/shan/src/moe-test/lib/bin/test-timestep_embedding")
set_tests_properties(test-timestep_embedding PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-timestep_embedding.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;302;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-pad-reflect-1d "/home/nxclab/shan/src/moe-test/lib/bin/test-pad-reflect-1d")
set_tests_properties(test-pad-reflect-1d PROPERTIES  _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;311;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv-transpose "/home/nxclab/shan/src/moe-test/lib/bin/test-conv-transpose")
set_tests_properties(test-conv-transpose PROPERTIES  _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;319;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv-transpose-1d "/home/nxclab/shan/src/moe-test/lib/bin/test-conv-transpose-1d")
set_tests_properties(test-conv-transpose-1d PROPERTIES  _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;326;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-dup "/home/nxclab/shan/src/moe-test/lib/bin/test-dup")
set_tests_properties(test-dup PROPERTIES  _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;335;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-rel-pos "/home/nxclab/shan/src/moe-test/lib/bin/test-rel-pos")
set_tests_properties(test-rel-pos PROPERTIES  _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;343;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-customop "/home/nxclab/shan/src/moe-test/lib/bin/test-customop")
set_tests_properties(test-customop PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-customop.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;364;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv1d "/home/nxclab/shan/src/moe-test/lib/bin/test-conv1d")
set_tests_properties(test-conv1d PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-conv1d.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;373;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv2d "/home/nxclab/shan/src/moe-test/lib/bin/test-conv2d")
set_tests_properties(test-conv2d PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-conv2d.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;383;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv2d-dw "/home/nxclab/shan/src/moe-test/lib/bin/test-conv2d-dw")
set_tests_properties(test-conv2d-dw PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-conv2d-dw.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;393;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-mul-mat "/home/nxclab/shan/src/moe-test/lib/bin/test-mul-mat")
set_tests_properties(test-mul-mat PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-mul-mat.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;403;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-backend-ops "/home/nxclab/shan/src/moe-test/lib/bin/test-backend-ops")
set_tests_properties(test-backend-ops PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-backend-ops.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;413;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
add_test(test-cont "/home/nxclab/shan/src/moe-test/lib/bin/test-cont")
set_tests_properties(test-cont PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-cont.profraw" _BACKTRACE_TRIPLES "/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;423;add_test;/home/nxclab/shan/src/moe-test/src/ggml/tests/CMakeLists.txt;0;")
